---
# handlers file for apache_s
- name: Restart apache2 from node_01
  service: name=apache2 state=restarted
  when: ansible_hostname == "node_01"

- name: Restart apache2 from node_02
  service: name=apache2 state=restarted
  when: ansible_hostname == "node_02"
