version: "3.8"
services:
  node_01:
    container_name: "Node_01"
    build: .
    ports:
      - "822:22"
    #restart: always
    volumes:
      - ./ssh_pub_key/pub_key:/home/ansible/.ssh/pub_key
    command: tail -f /dev/null
