version: "3.8"
services:
  node_01:
    container_name: "Node_01"
    build: .
    ports:
      - "822:22"
    volumes:
      - ./ssh_pub_key/:/home/ansible/ssh_pub_key/
    command: bash -c "
         cp /home/ansible/ssh_pub_key/authorized_keys /home/ansible/.ssh/authorized_keys
         && service ssh start
         && bash"
    tty: true
