version: "3.8"
services:
  master_node_01:
    container_name: "Master_Node_01"
    build:
      context: ./Master_Node
    image: master_node:latest
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
    hostname: master_node_01
    ports:
      - "822:22"
    volumes:
      - ./ssh_pub_key/:/home/ansible/ssh_pub_key/
      - ../ansible/:/home/ansible/ansible/
    environment:
      - ANSIBLE_CONFIG=/home/ansible/ansible/ansible.cfg
    command: bash -c "
         cp /home/ansible/.ssh/id_rsa.pub /home/ansible/ssh_pub_key/authorized_keys
         && service ssh start
         && bash"
    tty: true


  node_01:
    container_name: "Node_01"
    build: ./Node
    image: node:latest
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
    hostname: node_01
    depends_on:
      - master_node_01
    volumes:
      - ./ssh_pub_key/:/home/ansible/ssh_pub_key/
    command: bash -c "
         cp /home/ansible/ssh_pub_key/authorized_keys /home/ansible/.ssh/authorized_keys
         && service ssh start
         && bash"
    tty: true

  node_02:
    container_name: "Node_02"
    image: node:latest
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
    hostname: node_02
    depends_on:
      - node_01
    volumes:
      - ./ssh_pub_key/:/home/ansible/ssh_pub_key/
    command: bash -c "
         cp /home/ansible/ssh_pub_key/authorized_keys /home/ansible/.ssh/authorized_keys
         && service ssh start
         && bash"
    tty: true
