---
  - name: Install Apache Web Server and Enable services
    hosts: all
    become: yes


    tasks:
      - name: Install Apache Web server
        apt: name=apache2 update_cache=yes


      - name: start and Enable service httpd
        service: name=apache2 state=started enabled=yes
