---
# tasks file for apache_site
- block:
    - name: Install Apache Web server to node_01
      apt: name=apache2 update_cache=yes
    - name: start and Enable service apache2 on node_01
      service: name=apache2 state=started enabled=yes
  when: ansible_hostname == "node_01"
- block:
    - name: Install Apache Web server to node_02
      apt: name=apache2 update_cache=yes
    - name: start and Enable service apache2 on node_02
      service: name=apache2 state=started enabled=yes
  when: ansible_hostname == "node_02"

- include: remove_dir.yml
- include: copy_fails.yml
- include: generate_index_file.yml
- include: Restart_nodes.yml

- name: Delegate this task to any host
  shell: echo This host have name {{ inventory_hostname}} and node name {{ ansible_nodename}} >> /home/ansible/ansible/delegate.log
  delegate_to: 127.0.0.1
