---
  - name: Reboot nodes
    shell: sleep 3 && reboot now
    async: 1
    poll: 0

  - name: Wait rebooting nodes
    wait_for:
      host: "{{inventory_hostname}}"
      state: started
      delay: 2
      timeout: 20
    delegate_to: 127.0.0.1
